set_property MARK_DEBUG true [get_nets block_design_i/axi_timer_0_interrupt]
set_property MARK_DEBUG true [get_nets block_design_i/axi_quad_spi_0_ip2intc_irpt]
set_property MARK_DEBUG true [get_nets block_design_i/mdm_1_Interrupt]
set_property MARK_DEBUG true [get_nets block_design_i/axi_dma_0_mm2s_introut]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[0]}]
set_property MARK_DEBUG true [get_nets block_design_i/axi_dma_0_M_AXIS_MM2S_TVALID]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[8]}]
set_property MARK_DEBUG true [get_nets block_design_i/axi_dma_0_M_AXIS_MM2S_TREADY]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[25]}]
set_property MARK_DEBUG true [get_nets block_design_i/fir_compiler_0_M_AXIS_DATA_TVALID]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[0]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[4]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[7]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[1]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[11]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[6]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[3]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[10]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[14]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[15]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[13]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[9]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[8]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[2]}]
set_property MARK_DEBUG true [get_nets block_design_i/fir_compiler_0_M_AXIS_DATA_TREADY]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[5]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {block_design_i/leds[12]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[2]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list block_design_i/clk_wiz_1/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[0]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[1]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[2]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[3]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[4]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[5]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[6]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[7]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[8]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[9]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[10]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[11]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[12]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[13]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[14]} {block_design_i/axi_dma_0_M_AXIS_MM2S_TDATA[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[0]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[1]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[2]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[3]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[4]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[5]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[6]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[7]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[8]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[9]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[10]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[11]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[12]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[13]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[14]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[15]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[16]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[17]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[18]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[19]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[20]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[21]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[22]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[23]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[24]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[25]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[26]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[27]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[28]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[29]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[30]} {block_design_i/fir_compiler_0_M_AXIS_DATA_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {block_design_i/leds[0]} {block_design_i/leds[1]} {block_design_i/leds[2]} {block_design_i/leds[3]} {block_design_i/leds[4]} {block_design_i/leds[5]} {block_design_i/leds[6]} {block_design_i/leds[7]} {block_design_i/leds[8]} {block_design_i/leds[9]} {block_design_i/leds[10]} {block_design_i/leds[11]} {block_design_i/leds[12]} {block_design_i/leds[13]} {block_design_i/leds[14]} {block_design_i/leds[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list block_design_i/axi_dma_0_M_AXIS_MM2S_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list block_design_i/axi_dma_0_M_AXIS_MM2S_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list block_design_i/axi_dma_0_mm2s_introut]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list block_design_i/axi_quad_spi_0_ip2intc_irpt]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list block_design_i/axi_timer_0_interrupt]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list block_design_i/fir_compiler_0_M_AXIS_DATA_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list block_design_i/fir_compiler_0_M_AXIS_DATA_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list block_design_i/mdm_1_Interrupt]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
